examples/trivy.go, pkg/k8s/k8s.go, pkg/trivyk8s/trivyk8s.go
Fix https://github.com/aquasecurity/trivy-kubernetes/issues/13
=> Add automatic discovery for GVRs

pkg/trivyk8s/trivyk8s.go
Fix https://github.com/aquasecurity/trivy-kubernetes/issues/11
=> Fix providers authentication error

.github/workflows/release.yaml
Fix https://github.com/aquasecurity/trivy-kubernetes/actions/runs/2314471034
=> fix: release.yaml

examples/trivy.go, pkg/k8s/k8s.go, pkg/trivyk8s/trivyk8s.go
Fix https://github.com/aquasecurity/trivy-kubernetes/issues/21
=> feat: add get artifact

examples/trivy.go, pkg/k8s/k8s.go
Fix https://github.com/aquasecurity/trivy-kubernetes/issues/27
=> feat: add get current namespace

examples/trivy.go, pkg/k8s/k8s.go
=> feat: add context support

pkg/artifacts/artifacts.go, pkg/artifacts/artifacts_test.go, pkg/artifacts/testdata/fixtures/ephemeral.yaml, pkg/artifacts/testdata/fixtures/ephemeralcontainer.yaml, pkg/artifacts/testdata/fixtures/initcontainer.yaml
Close https://github.com/aquasecurity/trivy-kubernetes/issues/34
Close https://github.com/aquasecurity/trivy-kubernetes/issues/35
=> Add init and ephemeral containers

.github/ISSUE_TEMPLATE/config.yml
Fixes https://github.com/aquasecurity/trivy/issues/2206
=> chore: add issue template config

examples/trivy.go, go.mod, go.sum, pkg/trivyk8s/trivyk8s.go
Fix for but, not close -> https://github.com/aquasecurity/trivy/issues/2258
=> fix: log and continue if a resource is not found

pkg/jobs/builder.go, pkg/jobs/collector.go, pkg/trivyk8s/trivyk8s.go
Add support for pod tolerations
=> fix: support pod tolerations

examples/trivy.go, pkg/jobs/builder_test.go, pkg/jobs/template/node-collector.yaml
=> fix: update job template

pkg/jobs/builder.go, pkg/jobs/collector.go
Add support to update image ref
=> fix: update node collector job template

pkg/jobs/collector.go
=> fix: node collector job imageRef

pkg/jobs/collector.go
=> fix: trivy namepsace name

pkg/jobs/collector.go, pkg/jobs/util.go, pkg/jobs/util_test.go
label size : https://github.com/aquasecurity/trivy/issues/3668
=> fix: k8s label size

pkg/jobs/runner.go
=> feat: re-use context timeout

pkg/jobs/builder.go, pkg/jobs/collector.go
=> feat/add security context node-collector

pkg/jobs/builder_test.go, pkg/jobs/template/node-collector.yaml
update node-collector job resources
=> chore: update job resources

pkg/jobs/builder.go, pkg/jobs/collector.go
make node-collector volume configurable
=> feat: make node-collector volume configurable

pkg/jobs/builder_test.go, pkg/jobs/template/node-collector.yaml
=> chore: remove unused mount volumes

examples/trivy.go, pkg/trivyk8s/trivyk8s.go
Related: https://github.com/aquasecurity/trivy/issues/2901
=> fix: all-namespaces support

pkg/bom/model.go
cluster bom remove dependencies
=> feat: cluster bom remove dep

examples/trivy.go, pkg/bom/model.go, pkg/k8s/k8s.go, pkg/trivyk8s/trivyk8s.go
=> feat: list cluster bom

pkg/bom/model.go
=> refactor: cleanup and naming changes

pkg/trivyk8s/trivyk8s.go
=> refactor: pod info kind name

pkg/bom/model.go, pkg/k8s/k8s.go, pkg/trivyk8s/trivyk8s.go
=> feat: add component multi container support

examples/trivy.go, pkg/jobs/collector.go, pkg/trivyk8s/trivyk8s.go
node-collector custom namespace support
=> feat: node-collector-custom-namespace

examples/trivy.go, pkg/artifacts/artifacts.go, pkg/trivyk8s/trivyk8s.go
=> feat: skip node by label

pkg/trivyk8s/trivyk8s.go
node-collector exclude node by label
=> feat: exclude node by label

pkg/jobs/collector.go
=> refactor: method name typo

pkg/bom/model.go, pkg/k8s/k8s.go
=> feat: add kbom properties

pkg/k8s/k8s.go
=> feat: update kbom properties

pkg/k8s/k8s.go
=> feat: custom property support

pkg/jobs/logs.go
fix: scan job pod it not found on k8s-1.27.x
=> fix: scan job pod it not found on k8s-1.27.x

pkg/jobs/builder_test.go, pkg/jobs/template/node-collector.yaml
=> chore: update node-collector v0.0.7

pkg/trivyk8s/trivyk8s.go
support last applied configuration
=> fix: support last applied configuration

go.mod, go.sum, pkg/artifacts/artifacts.go, pkg/artifacts/artifacts_test.go, pkg/k8s/docker/config.go, pkg/k8s/docker/config_test.go, pkg/k8s/k8s.go, pkg/trivyk8s/trivyk8s.go
feat: private registry auto detect
=> feat: private registry auto detect

pkg/artifacts/artifacts.go, pkg/k8s/k8s.go
=> fix: add non empty credential

pkg/k8s/k8s.go
Related# https://github.com/aquasecurity/trivy/issues/5051
=> fix: support image pull secret

pkg/trivyk8s/trivyk8s.go
This pull request introduces an options configuration pattern to the TrivyK8S client and a new configuration option, `WithExcludeOwned`
Enabling `ExcludeOwned` allows users to disregard resources with ownerReferences.
=> feat: add options configuration and artifact listing enhancement

pkg/jobs/builder_test.go, pkg/jobs/template/node-collector.yaml
=> chore: bump node collector-0.8.0

pkg/k8s/k8s.go
kbom support addons label
Related: #https://github.com/aquasecurity/trivy/issues/5175
Related: #221
=> feat: kbom support addons label

pkg/k8s/k8s.go
fix  core component version #232
=> fix: core component version

pkg/jobs/builder.go, pkg/jobs/collector.go
=> fix: node collector priority class

pkg/trivyk8s/trivyk8s.go
fix: add k8s component artifacts
=> fix: add k8s component artifacts

utils/referance_test.go
=> test: ecr arn image ref

pkg/jobs/builder_test.go, pkg/jobs/template/node-collector.yaml
chore: bump node-collector v0.0.9
=> chore: bump node-collector v0.0.9

pkg/k8s/k8s.go, pkg/k8s/k8s_test.go, pkg/trivyk8s/trivyk8s.go
=> refactor: collect bom info

pkg/jobs/collector.go
=> fix: remove node selector

pkg/k8s/k8s.go
fix: name version cluster mode
=> fix: name version cluster mode

pkg/k8s/k8s.go
Ignore secret missing permission error
- Related #https://github.com/aquasecurity/trivy/issues/5682
=> fix: ignore secret missing permission error

examples/trivy.go, pkg/trivyk8s/trivyk8s.go
=> feat: node-collector image ref

examples/trivy.go, go.mod, go.sum, pkg/jobs/builder.go, pkg/jobs/builder_test.go, pkg/jobs/collector.go, pkg/jobs/runnable_job.go, pkg/jobs/template/node-collector.yaml
feat: job active deadline seconds support
=> feat: active deadline seconds support

go.mod, go.sum, pkg/artifacts/artifacts.go, pkg/jobs/collector.go, pkg/trivyk8s/trivyk8s.go
fix: ignore no init containers found in workload
- Related  https://github.com/aquasecurity/trivy/issues/5813
=> fix: ignore no init containers

pkg/jobs/builder.go, pkg/jobs/collector.go
fix: ignore no init containers update
=> fix: ignore no init containers update

pkg/jobs/collector.go
=> fix: use node-selector config

pkg/jobs/collector.go
fix: use node-selector and config
=> fix: use node-selector and config

pkg/artifacts/artifacts.go, utils/managed_fields.go, utils/managed_fields_test.go
- This PR aims to delete managed fields as they are not necessary for scans
=> feat: delete managed fields

pkg/k8s/k8s.go
Add rancher versioning support
- Related https://github.com/aquasecurity/trivy/issues/5987
=> feat: rancher rke2 version support

pkg/jobs/builder.go, pkg/jobs/collector.go
fix: use node selector param
- https://github.com/aquasecurity/trivy-operator/issues/1803
=> fix: use node selector param

pkg/jobs/builder.go, pkg/jobs/collector.go, pkg/trivyk8s/trivyk8s.go
Add support for pod affinity
Related to aquasecurity/trivy-operator#1835
=> fix: support pod affinity

pkg/trivyk8s/trivyk8s.go, pkg/trivyk8s/trivyk8s_test.go
feat: support exclude kinds/namespaces and include kinds/namespaces
Related:
- https://github.com/aquasecurity/trivy/issues/6195
- https://github.com/aquasecurity/trivy/issues/6196
=> feat: support exclude kinds/namespaces and include kinds/namespaces

pkg/jobs/builder.go
=> fix: node-collector resources

pkg/k8s/k8s.go
=> fix: skip non sha256 digest

pkg/jobs/builder.go
fix: add annotation node-collector job template spec
=> fix: add annotation node-collector job template spec

pkg/jobs/collector.go
avoid deleting non-default namespace
=> fix: avoid deleting non-default namespace

pkg/jobs/builder.go, pkg/jobs/collector.go
Add kubelet config via api support
- Related https://github.com/aquasecurity/trivy/issues/6602
=> feat: add kubelet config via api support

pkg/jobs/collector.go, pkg/jobs/collector_test.go
node-collector dynamic commands support
=> feat: node-collector dynamic commands support

pkg/trivyk8s/trivyk8s.go
feat: add embedded commands collector
=> feat: add embedded commands collector
