aquasecurity/trivy-kubernetes

- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
- pkg/trivyk8s/trivyk8s.go
Fix for https://github.com/aquasecurity/trivy/issues/2134
The idea is to work like `kubectl`, eg:
```
kubectl -n default get clusterroles/view
kubectl -n kube-system get clusterroles/view
```
> fix: ignore namespace for cluster level resources

- go.mod
- pkg/k8s/k8s.go
Fix for https://github.com/aquasecurity/trivy/issues/2148
The first version was checking for all GVRs of a given kind (eg: `batch/v1` and `batch/v1beta1`) to account for resources deployed on different versions.
But it is not necessary, different resources applied one in each version, will respond to both GVRs. (eg: cronjob "hello" returns for queries both in `batch/v1` and `batch/v1beta1` even though it was applied as `batch/v1beta1`, and the contrary is also true)
> Fix duplicate artifact

- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
Fix https://github.com/aquasecurity/trivy/issues/2196
> fix: if current namespace empty, returns default

- pkg/k8s/k8s.go
- pkg/trivyk8s/trivyk8s.go
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
Fix for https://github.com/aquasecurity/trivy/issues/2588
```
$ trivy k8s -n kube-system --report summary all
34 / 34 [-------------------------------------------------------------------------------------------------------] 100.00% 1 p/s
Summary Report for minikube
┌─────────────┬──────────────────────────────────────┬─────────────────────┬────────────────────┬───────────────────┐
│  Namespace  │               Resource               │   Vulnerabilities   │ Misconfigurations  │      Secrets      │
│             │                                      ├───┬────┬───┬────┬───┼───┬───┬───┬────┬───┼───┬───┬───┬───┬───┤
│             │                                      │ C │ H  │ M │ L  │ U │ C │ H │ M │ L  │ U │ C │ H │ M │ L │ U │ …
```
> fix: scanning control plane resources

- examples/trivy.go
- pkg/k8s/k8s.go
This is a dependent change for https://github.com/aquasecurity/trivy/issues/2522
Added option to specify kubeconfig file path when getting a k8s cluster
> chore: support kubeconfig option when getting a k8s cluster

- pkg/k8s/k8s.go
Fix for https://github.com/aquasecurity/trivy/issues/3063
This is a quick fix to avoid having `trivy k8s cluster` broken for newer kubernetes. I'll create two issues for we to discuss for the next release:
1 - should we support PSP for old clusters? 
2 - add support for PolicySecurityStanard, which is replacing PSP
> fix: remove support to PodSecurityPolicies

- .gitignore
- .idea/vcs.xml
- .idea/workspace.xml
- examples/trivy.go
- go.mod
- go.sum
- pkg/artifacts/artifacts_test.go
- pkg/jobs/builder.go
- pkg/jobs/builder_test.go
- pkg/jobs/collector.go
- pkg/jobs/loader.go
- pkg/jobs/loader_test.go
- pkg/jobs/logs.go
- pkg/jobs/runnable_job.go
- pkg/jobs/runner.go
- pkg/jobs/template/node-collector.yaml
- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
- pkg/trivyk8s/trivyk8s.go
Add support for triggering `node-collector` job in cluster.
the collector will collect info from node and output it.
require to support both for trivy and operator.
Related :
- [epic](https://github.com/aquasecurity/trivy/issues/2198)
-  [story](https://github.com/aquasecurity/trivy/issues/2201)
> Add support for Node Info

- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
Related: https://github.com/aquasecurity/trivy/issues/3825
> fix: current context title

- examples/trivy.go
- pkg/trivyk8s/trivyk8s.go
This pull request centers around an enhancement to the exclusion logic based on resource ownership. If the resource is owned by built-in workloads then the resource should be excluded.
This change ensures that resources owned by custom owners(Like CRDs) are not mistakenly excluded, while ensuring that resources owned by built-in workloads are excluded.
For example, consider the scenario where there are two pods: one named `my-pod`, which doesn't have any owners, and another named `pod-with-crd-owner`, which is created and managed by a custom owner(`acid.postgres.com/v1/postgresql`), and other regular pods owned by built-in workload kinds.
```
kubectl get pods -o custom-columns="NAME:.metadata.name,OWNER:.metadata.ownerReferences[*].kind"
NAME                                  OWNER
my-pod …
```
> feat: refining resource exclusion logic based on built-in or custom ownership

- examples/trivy.go
- pkg/trivyk8s/trivyk8s.go
Pods without owners are ignored because `ownerIsBuiltIn` is `true` by default. As a result the condition in if statement evaluates to true and the Pods without owners are ignored.
https://github.com/aquasecurity/trivy-kubernetes/blob/95e88d51f82b2e6951258fdb7ad2dacebbdcb803/pkg/trivyk8s/trivyk8s.go#L156
This PR adds `ownerExists` boolean variable to fix this issue.
```
go run examples/trivy.go
Current namespace: default
Scanning kind 'pods' with exclude-owned=true
Name: pod-with-crd-owner, Kind: Pod, Namespace: kube-system, Images: [nginx:latest]
```
```
go run examples/trivy.go
Current namespace: default
Scanning kind 'pods' with exclude-owned=true
Name: my-pod, Kind: Pod, Namespace: default, Images: [nginx:latest]
Name: pod-with-crd-owner, Kind: Pod, Namespace: kube-system, Images: …
```
> chore: fix issue caused by ownerIsBuiltIn being true by default

- pkg/trivyk8s/trivyk8s.go
In this change, I introduced a new function named 'hasOwner' to enhance the code.
This function streamlines the logic for determining whether a resource is owned by a built-in workload in Kubernetes.
It introduces no change in the overall behavior of the code.
cc @chen-keinan
> refactor: introduce 'hasOwner' function to reduce cognitive load

- pkg/jobs/builder.go
Because `JobBuilder` uses manual scheduling (setted `.spec.template.spec.nodeName` in `Job` spec) for "node" jobs (for example, `node-collector` jobs in aquasecurity/trivy-operator) , if node has taints with NoExecute effect and job doesn't have tolerations for them, `kube-controller-manager` would constantly create and delete job pods on node (manual scheduling for node -> create pod -> taint with `NoExecute` effect -> delete pod -> repeat).
Using [kubernetes.io/hostname](https://github.com/kubernetes/kubernetes/blob/61d87fdb2e6c656f3d7123570c78ada5dca59079/pkg/kubelet/kubelet_node_status.go#L217) label with `nodeSelector` would help to fix this issue.
> fix: constant job pod creation

- pkg/k8s/k8s.go
> fix: resolve image id

- pkg/k8s/k8s.go
> fix: add k8s component label

- examples/trivy.go
- pkg/trivyk8s/trivyk8s.go
fix: exclude bom info on namespace scope
> fix: exclude bom info on namespace scope

- examples/trivy.go
- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
This PR intents to allow end users to use custom QPS/Burst value with `trivy-kubernetes` library with wrapper functions
Output after QPS/Burst value set to 100/100 (after this PR)
```
Current namespace: default
Scanning cluster
Scan took 79.106125ms
```
Output with no overrides(before this PR)
```
Current namespace: default
Scanning cluster
Scan took 2.043902375s
```
@chen-keinan This PR fixes the issues we discussed in #262
> feat: allow adjustment of  QPS/Burst values

- pkg/artifacts/artifacts.go
- pkg/k8s/k8s.go
- utils/referance_test.go
handle non parsable images name
- Related https://github.com/aquasecurity/trivy/issues/5943
> fix: handle non parsable images name

- .github/workflows/build.yml
- .github/workflows/release.yaml
- go.mod
- pkg/artifacts/artifacts.go
- pkg/jobs/runnable_job.go
- pkg/jobs/runner.go
- pkg/k8s/k8s.go
fix: add logging un-parsed resource
> fix: add logging un-parsed resource

- examples/trivy.go
- pkg/trivyk8s/trivyk8s.go
- pkg/trivyk8s/trivyk8s_test.go
support exclude and include kinds and namespaces for bom
> feat: support exclude and include kinds and namespaces for bom

- examples/trivy.go
- go.mod
- go.sum
- pkg/trivyk8s/trivyk8s.go
> refactor: use slog

- pkg/k8s/k8s.go
Use of specified context to obtain cluster name
- Related https://github.com/aquasecurity/trivy/issues/6643
> fix: use of specified context to obtain cluster name

- pkg/trivyk8s/trivyk8s.go
Handle resource has no permission error
- Related https://github.com/aquasecurity/trivy/issues/6692
> fix: handle resource has no permission error

- pkg/k8s/k8s.go
This PR fixes [the bug reported here](https://github.com/aquasecurity/trivy/discussions/6928) by skipping empty references in `imagePullSecrets` array.
> fix(k8s): skip empty image pull secrets

- pkg/jobs/collector.go
fix: use embedded when command path not found
- Related https://github.com/aquasecurity/trivy/issues/6602
> fix: use embedded when command path not found

- pkg/k8s/k8s.go
Ignore nodes when listing permission is not allowed
- Related https://github.com/aquasecurity/trivy/issues/6692
> fix: ignore nodes when listing permission is not allowed

- pkg/jobs/runnable_job.go
In Kubernetes v1.31.* the diagram of transitions looks like below. 
so we can complete the job after the first success, but we should wait for all pods are terminated.
the docs: [Transition of "status.conditions"](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3998-job-success-completion-policy#transition-of-statusconditions)
> fix: add new status conditions for k8s v1.31

- pkg/jobs/collector.go
- pkg/jobs/collector_test.go
This PR adds default command for unknown platforms.
the test cases was updated. I couldn't find `aks` platfrom in Trivy-check kubernetes commands: https://github.com/aquasecurity/trivy-checks/blob/main/commands/kubernetes/.
so I've changed `aks` to `rke2`, and using `aks` as unknown platform.
- https://github.com/aquasecurity/trivy/issues/7786
> feat: add default commands for unknown platform

- pkg/jobs/collector.go
this PR adds a node name to improve troubleshooting
> chore: improve log for node-collector error

- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
This PR introduces the ability to retrieve pods from k8s that are marked as controller components (based on the label "app.kubernetes.io/component=controller").
The resource name and version are determined based on available labels, if present.
Prepare:
```sh
$ kind delete cluster && kind create cluster && kubectl wait --for=condition=Ready --all nodes
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.0/deploy/static/provider/cloud/deploy.yaml
$ trivy k8s --format cyclonedx -o kbom.cdx --report all
```
Before:
```sh
$ trivy sbom kbom.cdx
...
Report Summary
┌──────────────────────┬────────────┬─────────────────┐
│        Target        │    Type    │ Vulnerabilities │
├──────────────────────┼────────────┼─────────────────┤
│ kbom.cdx (debian 12) …
```
> feat: add ingress-nginx controller components

- .github/workflows/build.yml
- .github/workflows/release.yaml
We have to update deprecated runners based on https://github.com/actions/runner-images/issues/11101
> ci: update deprecated runners

- .github/workflows/build.yml
- .github/workflows/release.yaml
- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
This PR fixes:
1. Enhanced Image Data Source
Previously, image information was retrieved only from `pod.Status.ContainerStatuses`, which does not always contain complete data.
Also `pod.status.containerStatuses` sometimes displayed image name incorrectly when image has multiple tags on the node: https://github.com/kubernetes/kubernetes/issues/74081
Now, both `pod.Spec` and `pod.Status` are used to ensure accurate image retrieval.
2. Fixed Parsing of Tags and Digests
When an image contained both a tag and a digest, the parser incorrectly extracted the digest instead of the version. 
the same issue was fixed in Trivy-operator: https://github.com/aquasecurity/trivy-operator/pull/2418/
We implemented it ourselves because it's a known issue in go-containerregistry, this one is closed as `not …
> fix: correct compare docker version

- pkg/trivyk8s/trivyk8s.go
- pkg/trivyk8s/trivyk8s_test.go
This PR removes the logic for scanning Kubernetes resources via the `last-applied-configuration` annotation.
As of Kubernetes v1.25, resources that previously relied on this annotation have been removed, making this scanning method unuseful.
This PR is created in favor of discussion in comments: https://github.com/aquasecurity/trivy/pull/8456
> fix: remove using `last-applied-configuration`

- .github/workflows/build.yml
- pkg/jobs/logs.go
- pkg/jobs/util.go
- pkg/k8s/docker/config.go
- pkg/k8s/k8s.go
- pkg/k8s/k8s_test.go
This PR bumps up golangci-lint to version v2 and github action to support it.
It made in favor of Trivy https://github.com/aquasecurity/trivy/pull/8766
> chore(deps): bump golangci-lint to v2
